/**
 * Dados estáticos do Brasileirão Série A 2026 extraídos de ge.globo.com.
 * Logos: CDN oficial Globo (s.sde.globo.com) — qualidade oficial, sem CORS em <img>.
 */

export const GLOBO_TEAM_LOGOS: Record<string, string> = {
  flamengo: 'https://s.sde.globo.com/media/organizations/2018/04/10/Flamengo-2018.svg',
  mirassol: 'https://s.sde.globo.com/media/organizations/2024/08/20/mirassol-novo-svg-71690.svg',
  botafogo: 'https://s.sde.globo.com/media/organizations/2019/02/04/botafogo-svg.svg',
  vitoria: 'https://s.sde.globo.com/media/organizations/2025/12/18/Vitoria_2025.svg',
  bahia: 'https://s.sde.globo.com/media/organizations/2018/03/11/bahia.svg',
  chapecoense: 'https://s.sde.globo.com/media/organizations/2021/06/21/CHAPECOENSE-2018.svg',
  palmeiras: 'https://s.sde.globo.com/media/organizations/2014/04/14/palmeiras_60x60.png',
  fluminense: 'https://s.sde.globo.com/media/organizations/2014/04/14/fluminense_60x60.png',
  gremio: 'https://s.sde.globo.com/media/organizations/2014/04/14/gremio_60x60.png',
  atleticomineiro:
    'https://s.sde.globo.com/media/organizations/2017/11/23/Atletico-Mineiro-escudo65px.png',
  atleticomg:
    'https://s.sde.globo.com/media/organizations/2017/11/23/Atletico-Mineiro-escudo65px.png',
  santos: 'https://s.sde.globo.com/media/organizations/2014/04/14/santos_60x60.png',
  vascodagama: 'https://s.sde.globo.com/media/organizations/2021/09/04/ESCUDO-VASCO-RGB_65px.png',
  vasco: 'https://s.sde.globo.com/media/organizations/2021/09/04/ESCUDO-VASCO-RGB_65px.png',
  saopaulo: 'https://s.sde.globo.com/media/organizations/2014/04/14/sao_paulo_60x60.png',
  remo: 'https://s.sde.globo.com/media/organizations/2013/10/11/REmo-65.png',
  redbullbragantino: 'https://s.sde.globo.com/media/organizations/2020/01/01/65.png',
  bragantino: 'https://s.sde.globo.com/media/organizations/2020/01/01/65.png',
  athleticoparanaense:
    'https://s.sde.globo.com/media/organizations/2019/09/09/Athletico-PR-65x65.png',
  coritiba: 'https://s.sde.globo.com/media/organizations/2017/03/29/coritiba65.png',
  cruzeiro: 'https://s.sde.globo.com/media/organizations/2021/02/13/65_cruzeiro-2021.png',
  corinthians:
    'https://s.sde.globo.com/media/organizations/2024/10/09/Corinthians-2024-65_IYhgZ1u.png',
  internacional: 'https://s.sde.globo.com/media/organizations/2016/05/03/inter65.png',
  fortaleza: 'https://s.sde.globo.com/media/organizations/2014/04/14/fortaleza_60x60.png',
  juventude: 'https://s.sde.globo.com/media/organizations/2021/06/21/chapecoense65.png',
  sportrecife: 'https://s.sde.globo.com/media/organizations/2014/04/14/sport_60x60.png',
};

export interface ArtilheiroRow {
  rank: number;
  nome: string;
  posicao: string;
  clube: string;
  clubeLogo: string;
  foto: string;
  gols: number;
}

/** Artilharia do Brasileirão Série A 2026 — Rodada 3 (fonte: ge.globo.com) */
export const ARTILHARIA_SERIE_A: ArtilheiroRow[] = [
  {
    rank: 1,
    nome: 'Danilo',
    posicao: 'Volante',
    clube: 'Botafogo',
    clubeLogo: GLOBO_TEAM_LOGOS.botafogo,
    foto: 'https://s.sde.globo.com/media/person_role/2025/07/18/photo_140x140_yLk4Oay.png',
    gols: 4,
  },
  {
    rank: 1,
    nome: 'Carlos Vinícius',
    posicao: 'Atacante',
    clube: 'Grêmio',
    clubeLogo: GLOBO_TEAM_LOGOS.gremio,
    foto: 'https://s.sde.globo.com/media/person_role/2026/02/09/photo_140x140_GTU3C2P.png',
    gols: 4,
  },
  {
    rank: 3,
    nome: 'Breno Lopes',
    posicao: 'Atacante',
    clube: 'Coritiba',
    clubeLogo: GLOBO_TEAM_LOGOS.coritiba,
    foto: 'https://s.sde.globo.com/media/person_role/2026/02/09/photo_140x140_q6kEOrG.png',
    gols: 3,
  },
  {
    rank: 4,
    nome: 'Lucho Acosta',
    posicao: 'Meia',
    clube: 'Fluminense',
    clubeLogo: GLOBO_TEAM_LOGOS.fluminense,
    foto: 'https://s.sde.globo.com/media/person_role/2026/02/20/photo_140x140_SrmZFdk.png',
    gols: 2,
  },
  {
    rank: 4,
    nome: 'Calleri',
    posicao: 'Atacante',
    clube: 'São Paulo',
    clubeLogo: GLOBO_TEAM_LOGOS.saopaulo,
    foto: 'https://s.sde.globo.com/media/person_role/2026/02/20/photo_140x140_2u6NnKV.png',
    gols: 2,
  },
  {
    rank: 4,
    nome: 'Jean Carlos',
    posicao: 'Meia',
    clube: 'Chapecoense',
    clubeLogo: GLOBO_TEAM_LOGOS.chapecoense,
    foto: 'https://s.sde.globo.com/media/person_role/2025/08/01/photo_140x140_4IWx3fP.png',
    gols: 2,
  },
  {
    rank: 4,
    nome: 'Nathan Fogaça',
    posicao: 'Atacante',
    clube: 'Mirassol',
    clubeLogo: GLOBO_TEAM_LOGOS.mirassol,
    foto: 'https://s.sde.globo.com/media/person_role/2026/02/09/photo_140x140_dP21GPQ.png',
    gols: 2,
  },
  {
    rank: 4,
    nome: 'Walter Clar',
    posicao: 'Lateral-Esq.',
    clube: 'Chapecoense',
    clubeLogo: GLOBO_TEAM_LOGOS.chapecoense,
    foto: 'https://s.sde.globo.com/media/person_role/2024/10/16/photo_140x140_apk0JWi.png',
    gols: 2,
  },
  {
    rank: 4,
    nome: 'Alef Manga',
    posicao: 'Atacante',
    clube: 'Remo',
    clubeLogo: GLOBO_TEAM_LOGOS.remo,
    foto: 'https://s.sde.globo.com/media/person_role/2026/02/09/photo_140x140_vvMsJPI.png',
    gols: 2,
  },
  {
    rank: 4,
    nome: 'Vitor Roque',
    posicao: 'Atacante',
    clube: 'Palmeiras',
    clubeLogo: GLOBO_TEAM_LOGOS.palmeiras,
    foto: 'https://s.sde.globo.com/media/person_role/2025/04/01/photo_140x140_UbLy5Jq.png',
    gols: 2,
  },
  {
    rank: 4,
    nome: 'Gustavo Gómez',
    posicao: 'Zagueiro',
    clube: 'Palmeiras',
    clubeLogo: GLOBO_TEAM_LOGOS.palmeiras,
    foto: 'https://s.sde.globo.com/media/person_role/2025/04/01/photo_140x140_jyEJbYJ.png',
    gols: 2,
  },
];

export interface TabelaStaticRow {
  posicao: number;
  nomeTime: string;
  logo: string;
  pts: number;
  jogos: number;
  vitorias: number;
  empates: number;
  derrotas: number;
  gp: number;
  gc: number;
  sg: number;
}

/** Classificação Série A 2026 — Rodada 3 (fonte: ge.globo.com) */
export const TABELA_SERIE_A_STATIC: TabelaStaticRow[] = [
  {
    posicao: 1,
    nomeTime: 'Palmeiras',
    logo: GLOBO_TEAM_LOGOS.palmeiras,
    pts: 7,
    jogos: 3,
    vitorias: 2,
    empates: 1,
    derrotas: 0,
    gp: 10,
    gc: 4,
    sg: 6,
  },
  {
    posicao: 2,
    nomeTime: 'São Paulo',
    logo: GLOBO_TEAM_LOGOS.saopaulo,
    pts: 7,
    jogos: 3,
    vitorias: 2,
    empates: 1,
    derrotas: 0,
    gp: 5,
    gc: 2,
    sg: 3,
  },
  {
    posicao: 3,
    nomeTime: 'Fluminense',
    logo: GLOBO_TEAM_LOGOS.fluminense,
    pts: 7,
    jogos: 3,
    vitorias: 2,
    empates: 1,
    derrotas: 0,
    gp: 4,
    gc: 2,
    sg: 2,
  },
  {
    posicao: 4,
    nomeTime: 'Bahia',
    logo: GLOBO_TEAM_LOGOS.bahia,
    pts: 7,
    jogos: 3,
    vitorias: 2,
    empates: 1,
    derrotas: 0,
    gp: 4,
    gc: 2,
    sg: 2,
  },
  {
    posicao: 5,
    nomeTime: 'Corinthians',
    logo: GLOBO_TEAM_LOGOS.corinthians,
    pts: 6,
    jogos: 3,
    vitorias: 2,
    empates: 0,
    derrotas: 1,
    gp: 4,
    gc: 2,
    sg: 2,
  },
  {
    posicao: 6,
    nomeTime: 'Athletico-PR',
    logo: GLOBO_TEAM_LOGOS.athleticoparanaense,
    pts: 6,
    jogos: 3,
    vitorias: 2,
    empates: 0,
    derrotas: 1,
    gp: 3,
    gc: 2,
    sg: 1,
  },
  {
    posicao: 7,
    nomeTime: 'Bragantino',
    logo: GLOBO_TEAM_LOGOS.bragantino,
    pts: 6,
    jogos: 3,
    vitorias: 2,
    empates: 0,
    derrotas: 1,
    gp: 2,
    gc: 2,
    sg: 0,
  },
  {
    posicao: 8,
    nomeTime: 'Chapecoense',
    logo: GLOBO_TEAM_LOGOS.chapecoense,
    pts: 5,
    jogos: 3,
    vitorias: 1,
    empates: 2,
    derrotas: 0,
    gp: 8,
    gc: 6,
    sg: 2,
  },
  {
    posicao: 9,
    nomeTime: 'Mirassol',
    logo: GLOBO_TEAM_LOGOS.mirassol,
    pts: 5,
    jogos: 3,
    vitorias: 1,
    empates: 2,
    derrotas: 0,
    gp: 6,
    gc: 5,
    sg: 1,
  },
  {
    posicao: 10,
    nomeTime: 'Coritiba',
    logo: GLOBO_TEAM_LOGOS.coritiba,
    pts: 4,
    jogos: 3,
    vitorias: 1,
    empates: 1,
    derrotas: 1,
    gp: 5,
    gc: 5,
    sg: 0,
  },
  {
    posicao: 11,
    nomeTime: 'Flamengo',
    logo: GLOBO_TEAM_LOGOS.flamengo,
    pts: 4,
    jogos: 3,
    vitorias: 1,
    empates: 1,
    derrotas: 1,
    gp: 4,
    gc: 4,
    sg: 0,
  },
  {
    posicao: 12,
    nomeTime: 'Botafogo',
    logo: GLOBO_TEAM_LOGOS.botafogo,
    pts: 3,
    jogos: 3,
    vitorias: 1,
    empates: 0,
    derrotas: 2,
    gp: 7,
    gc: 6,
    sg: 1,
  },
  {
    posicao: 13,
    nomeTime: 'Grêmio',
    logo: GLOBO_TEAM_LOGOS.gremio,
    pts: 3,
    jogos: 3,
    vitorias: 1,
    empates: 0,
    derrotas: 2,
    gp: 6,
    gc: 7,
    sg: -1,
  },
  {
    posicao: 14,
    nomeTime: 'Vitória',
    logo: GLOBO_TEAM_LOGOS.vitoria,
    pts: 2,
    jogos: 3,
    vitorias: 0,
    empates: 2,
    derrotas: 1,
    gp: 5,
    gc: 6,
    sg: -1,
  },
  {
    posicao: 15,
    nomeTime: 'Atlético-MG',
    logo: GLOBO_TEAM_LOGOS.atleticomineiro,
    pts: 2,
    jogos: 3,
    vitorias: 0,
    empates: 2,
    derrotas: 1,
    gp: 5,
    gc: 7,
    sg: -2,
  },
  {
    posicao: 16,
    nomeTime: 'Remo',
    logo: GLOBO_TEAM_LOGOS.remo,
    pts: 1,
    jogos: 3,
    vitorias: 0,
    empates: 1,
    derrotas: 2,
    gp: 2,
    gc: 4,
    sg: -2,
  },
  {
    posicao: 17,
    nomeTime: 'Vasco',
    logo: GLOBO_TEAM_LOGOS.vascodagama,
    pts: 1,
    jogos: 3,
    vitorias: 0,
    empates: 1,
    derrotas: 2,
    gp: 4,
    gc: 7,
    sg: -3,
  },
  {
    posicao: 18,
    nomeTime: 'Santos',
    logo: GLOBO_TEAM_LOGOS.santos,
    pts: 0,
    jogos: 3,
    vitorias: 0,
    empates: 0,
    derrotas: 3,
    gp: 3,
    gc: 8,
    sg: -5,
  },
  {
    posicao: 19,
    nomeTime: 'Internacional',
    logo: GLOBO_TEAM_LOGOS.internacional,
    pts: 0,
    jogos: 3,
    vitorias: 0,
    empates: 0,
    derrotas: 3,
    gp: 2,
    gc: 5,
    sg: -3,
  },
  {
    posicao: 20,
    nomeTime: 'Cruzeiro',
    logo: GLOBO_TEAM_LOGOS.cruzeiro,
    pts: 0,
    jogos: 3,
    vitorias: 0,
    empates: 0,
    derrotas: 3,
    gp: 0,
    gc: 0,
    sg: 0,
  },
];
