/**
 * services/brasileiraoData.ts
 * Dados do Brasileirão Série A 2025 — tabela de classificação e próximos jogos
 * Fonte de referência: ge.globo.com/futebol/brasileirao-serie-a/
 * Última atualização: Rodada 4 (25/02/2025)
 */

// --- Team logos (escudos oficiais via API pública) ---

const BADGE_BASE = 'https://s.sde.globo.com/media/organizations';

export const TEAM_BADGES: Record<string, string> = {
  Flamengo: `${BADGE_BASE}/2024/03/11/flamengo.svg`,
  Palmeiras: `${BADGE_BASE}/2024/03/11/palmeiras.svg`,
  Botafogo: `${BADGE_BASE}/2024/03/11/botafogo.svg`,
  'São Paulo': `${BADGE_BASE}/2024/03/11/sao-paulo.svg`,
  Fluminense: `${BADGE_BASE}/2024/03/11/fluminense.svg`,
  Internacional: `${BADGE_BASE}/2024/03/11/internacional.svg`,
  'Atlético-MG': `${BADGE_BASE}/2024/03/11/atletico-mg.svg`,
  Grêmio: `${BADGE_BASE}/2024/03/11/gremio.svg`,
  Corinthians: `${BADGE_BASE}/2024/03/11/corinthians.svg`,
  Cruzeiro: `${BADGE_BASE}/2024/03/11/cruzeiro.svg`,
  Fortaleza: `${BADGE_BASE}/2024/03/11/fortaleza.svg`,
  Bahia: `${BADGE_BASE}/2024/03/11/bahia.svg`,
  Vasco: `${BADGE_BASE}/2024/03/11/vasco.svg`,
  'Athletico-PR': `${BADGE_BASE}/2024/03/11/athletico-pr.svg`,
  Bragantino: `${BADGE_BASE}/2024/03/11/red-bull-bragantino.svg`,
  Santos: `${BADGE_BASE}/2024/03/11/santos.svg`,
  Vitória: `${BADGE_BASE}/2024/03/11/vitoria.svg`,
  Sport: `${BADGE_BASE}/2024/03/11/sport.svg`,
  Mirassol: `${BADGE_BASE}/2024/03/11/mirassol.svg`,
  Coritiba: `${BADGE_BASE}/2024/03/11/coritiba.svg`,
  Remo: `${BADGE_BASE}/2024/03/11/remo.svg`,
  Ceará: `${BADGE_BASE}/2024/03/11/ceara.svg`,
};

// Fallback: usar primeira letra como iniciais se badge não carregar
export function getTeamBadge(teamName: string): string | null {
  return TEAM_BADGES[teamName] || null;
}

// --- Classificação (Rodada 4) ---

export interface ClassificacaoRow {
  pos: number;
  team: string;
  pts: number;
  j: number; // jogos
  v: number; // vitórias
  e: number; // empates
  d: number; // derrotas
  gp: number; // gols pró
  gc: number; // gols contra
  sg: number; // saldo de gols
  form: ('W' | 'D' | 'L')[]; // últimos 5 jogos
}

export const CLASSIFICACAO_BRASILEIRAO: ClassificacaoRow[] = [
  {
    pos: 1,
    team: 'São Paulo',
    pts: 10,
    j: 4,
    v: 3,
    e: 1,
    d: 0,
    gp: 7,
    gc: 2,
    sg: 5,
    form: ['W', 'W', 'D', 'W'],
  },
  {
    pos: 2,
    team: 'Flamengo',
    pts: 10,
    j: 4,
    v: 3,
    e: 1,
    d: 0,
    gp: 8,
    gc: 3,
    sg: 5,
    form: ['W', 'D', 'W', 'W'],
  },
  {
    pos: 3,
    team: 'Palmeiras',
    pts: 9,
    j: 4,
    v: 3,
    e: 0,
    d: 1,
    gp: 6,
    gc: 3,
    sg: 3,
    form: ['W', 'W', 'L', 'W'],
  },
  {
    pos: 4,
    team: 'Botafogo',
    pts: 9,
    j: 4,
    v: 3,
    e: 0,
    d: 1,
    gp: 7,
    gc: 4,
    sg: 3,
    form: ['W', 'L', 'W', 'W'],
  },
  {
    pos: 5,
    team: 'Fortaleza',
    pts: 7,
    j: 4,
    v: 2,
    e: 1,
    d: 1,
    gp: 5,
    gc: 3,
    sg: 2,
    form: ['W', 'D', 'L', 'W'],
  },
  {
    pos: 6,
    team: 'Bahia',
    pts: 7,
    j: 4,
    v: 2,
    e: 1,
    d: 1,
    gp: 4,
    gc: 2,
    sg: 2,
    form: ['D', 'W', 'W', 'L'],
  },
  {
    pos: 7,
    team: 'Internacional',
    pts: 7,
    j: 4,
    v: 2,
    e: 1,
    d: 1,
    gp: 5,
    gc: 4,
    sg: 1,
    form: ['W', 'W', 'L', 'D'],
  },
  {
    pos: 8,
    team: 'Cruzeiro',
    pts: 6,
    j: 4,
    v: 2,
    e: 0,
    d: 2,
    gp: 5,
    gc: 4,
    sg: 1,
    form: ['L', 'W', 'W', 'L'],
  },
  {
    pos: 9,
    team: 'Atlético-MG',
    pts: 6,
    j: 4,
    v: 2,
    e: 0,
    d: 2,
    gp: 4,
    gc: 4,
    sg: 0,
    form: ['W', 'L', 'L', 'W'],
  },
  {
    pos: 10,
    team: 'Grêmio',
    pts: 5,
    j: 4,
    v: 1,
    e: 2,
    d: 1,
    gp: 4,
    gc: 3,
    sg: 1,
    form: ['D', 'W', 'D', 'L'],
  },
  {
    pos: 11,
    team: 'Corinthians',
    pts: 5,
    j: 4,
    v: 1,
    e: 2,
    d: 1,
    gp: 3,
    gc: 3,
    sg: 0,
    form: ['D', 'L', 'W', 'D'],
  },
  {
    pos: 12,
    team: 'Vasco',
    pts: 5,
    j: 4,
    v: 1,
    e: 2,
    d: 1,
    gp: 4,
    gc: 5,
    sg: -1,
    form: ['L', 'D', 'W', 'D'],
  },
  {
    pos: 13,
    team: 'Santos',
    pts: 4,
    j: 4,
    v: 1,
    e: 1,
    d: 2,
    gp: 3,
    gc: 4,
    sg: -1,
    form: ['W', 'L', 'D', 'L'],
  },
  {
    pos: 14,
    team: 'Bragantino',
    pts: 4,
    j: 4,
    v: 1,
    e: 1,
    d: 2,
    gp: 3,
    gc: 5,
    sg: -2,
    form: ['L', 'W', 'L', 'D'],
  },
  {
    pos: 15,
    team: 'Athletico-PR',
    pts: 3,
    j: 4,
    v: 0,
    e: 3,
    d: 1,
    gp: 3,
    gc: 4,
    sg: -1,
    form: ['D', 'D', 'L', 'D'],
  },
  {
    pos: 16,
    team: 'Vitória',
    pts: 3,
    j: 4,
    v: 1,
    e: 0,
    d: 3,
    gp: 2,
    gc: 5,
    sg: -3,
    form: ['L', 'W', 'L', 'L'],
  },
  {
    pos: 17,
    team: 'Sport',
    pts: 2,
    j: 4,
    v: 0,
    e: 2,
    d: 2,
    gp: 2,
    gc: 4,
    sg: -2,
    form: ['D', 'L', 'D', 'L'],
  },
  {
    pos: 18,
    team: 'Coritiba',
    pts: 2,
    j: 4,
    v: 0,
    e: 2,
    d: 2,
    gp: 2,
    gc: 5,
    sg: -3,
    form: ['D', 'L', 'L', 'D'],
  },
  {
    pos: 19,
    team: 'Mirassol',
    pts: 1,
    j: 4,
    v: 0,
    e: 1,
    d: 3,
    gp: 2,
    gc: 6,
    sg: -4,
    form: ['L', 'D', 'L', 'L'],
  },
  {
    pos: 20,
    team: 'Remo',
    pts: 1,
    j: 4,
    v: 0,
    e: 1,
    d: 3,
    gp: 1,
    gc: 5,
    sg: -4,
    form: ['L', 'L', 'D', 'L'],
  },
];

// --- Resultados Rodada 4 (25/02/2025) ---

export interface MatchResult {
  home: string;
  away: string;
  homeScore: number;
  awayScore: number;
  date: string;
  time: string;
  venue: string;
  round: number;
  status: 'FT' | 'LIVE' | 'HT' | 'SCHED';
  elapsed?: number;
}

export const RESULTADOS_RODADA_4: MatchResult[] = [
  {
    home: 'São Paulo',
    away: 'Coritiba',
    homeScore: 1,
    awayScore: 0,
    date: '2025-02-25',
    time: '19:00',
    venue: 'MorumBIS',
    round: 4,
    status: 'FT',
  },
  {
    home: 'Bragantino',
    away: 'Athletico-PR',
    homeScore: 1,
    awayScore: 1,
    date: '2025-02-25',
    time: '19:00',
    venue: 'Nabi Abi Chedid',
    round: 4,
    status: 'FT',
  },
  {
    home: 'Remo',
    away: 'Internacional',
    homeScore: 0,
    awayScore: 0,
    date: '2025-02-25',
    time: '21:30',
    venue: 'Mangueirão',
    round: 4,
    status: 'FT',
  },
  {
    home: 'Flamengo',
    away: 'Bahia',
    homeScore: 2,
    awayScore: 1,
    date: '2025-02-25',
    time: '21:30',
    venue: 'Maracanã',
    round: 4,
    status: 'FT',
  },
  {
    home: 'Palmeiras',
    away: 'Corinthians',
    homeScore: 3,
    awayScore: 1,
    date: '2025-02-25',
    time: '21:30',
    venue: 'Allianz Parque',
    round: 4,
    status: 'FT',
  },
  {
    home: 'Botafogo',
    away: 'Cruzeiro',
    homeScore: 2,
    awayScore: 0,
    date: '2025-02-24',
    time: '20:00',
    venue: 'Nilton Santos',
    round: 4,
    status: 'FT',
  },
  {
    home: 'Grêmio',
    away: 'Vitória',
    homeScore: 1,
    awayScore: 0,
    date: '2025-02-24',
    time: '20:00',
    venue: 'Arena do Grêmio',
    round: 4,
    status: 'FT',
  },
  {
    home: 'Fortaleza',
    away: 'Santos',
    homeScore: 2,
    awayScore: 1,
    date: '2025-02-24',
    time: '18:30',
    venue: 'Castelão',
    round: 4,
    status: 'FT',
  },
  {
    home: 'Atlético-MG',
    away: 'Mirassol',
    homeScore: 2,
    awayScore: 0,
    date: '2025-02-23',
    time: '16:00',
    venue: 'Arena MRV',
    round: 4,
    status: 'FT',
  },
  {
    home: 'Sport',
    away: 'Vasco',
    homeScore: 1,
    awayScore: 1,
    date: '2025-02-23',
    time: '18:30',
    venue: 'Ilha do Retiro',
    round: 4,
    status: 'FT',
  },
];

// --- Próximos Jogos — Rodada 5 ---

export const PROXIMOS_JOGOS_RODADA_5: MatchResult[] = [
  {
    home: 'Corinthians',
    away: 'Flamengo',
    homeScore: 0,
    awayScore: 0,
    date: '2025-03-01',
    time: '16:00',
    venue: 'Neo Química Arena',
    round: 5,
    status: 'SCHED',
  },
  {
    home: 'Bahia',
    away: 'Botafogo',
    homeScore: 0,
    awayScore: 0,
    date: '2025-03-01',
    time: '18:30',
    venue: 'Arena Fonte Nova',
    round: 5,
    status: 'SCHED',
  },
  {
    home: 'Internacional',
    away: 'Palmeiras',
    homeScore: 0,
    awayScore: 0,
    date: '2025-03-01',
    time: '18:30',
    venue: 'Beira-Rio',
    round: 5,
    status: 'SCHED',
  },
  {
    home: 'Santos',
    away: 'São Paulo',
    homeScore: 0,
    awayScore: 0,
    date: '2025-03-01',
    time: '21:00',
    venue: 'Vila Belmiro',
    round: 5,
    status: 'SCHED',
  },
  {
    home: 'Cruzeiro',
    away: 'Fortaleza',
    homeScore: 0,
    awayScore: 0,
    date: '2025-03-02',
    time: '16:00',
    venue: 'Mineirão',
    round: 5,
    status: 'SCHED',
  },
  {
    home: 'Vasco',
    away: 'Grêmio',
    homeScore: 0,
    awayScore: 0,
    date: '2025-03-02',
    time: '18:30',
    venue: 'São Januário',
    round: 5,
    status: 'SCHED',
  },
  {
    home: 'Coritiba',
    away: 'Atlético-MG',
    homeScore: 0,
    awayScore: 0,
    date: '2025-03-02',
    time: '18:30',
    venue: 'Couto Pereira',
    round: 5,
    status: 'SCHED',
  },
  {
    home: 'Athletico-PR',
    away: 'Sport',
    homeScore: 0,
    awayScore: 0,
    date: '2025-03-02',
    time: '20:00',
    venue: 'Ligga Arena',
    round: 5,
    status: 'SCHED',
  },
  {
    home: 'Mirassol',
    away: 'Remo',
    homeScore: 0,
    awayScore: 0,
    date: '2025-03-02',
    time: '20:00',
    venue: 'Est. Campos Maia',
    round: 5,
    status: 'SCHED',
  },
  {
    home: 'Vitória',
    away: 'Bragantino',
    homeScore: 0,
    awayScore: 0,
    date: '2025-03-02',
    time: '20:00',
    venue: 'Barradão',
    round: 5,
    status: 'SCHED',
  },
];

// --- Próximos Jogos — Rodada 6 ---

export const PROXIMOS_JOGOS_RODADA_6: MatchResult[] = [
  {
    home: 'Flamengo',
    away: 'Palmeiras',
    homeScore: 0,
    awayScore: 0,
    date: '2025-03-08',
    time: '16:00',
    venue: 'Maracanã',
    round: 6,
    status: 'SCHED',
  },
  {
    home: 'São Paulo',
    away: 'Internacional',
    homeScore: 0,
    awayScore: 0,
    date: '2025-03-08',
    time: '18:30',
    venue: 'MorumBIS',
    round: 6,
    status: 'SCHED',
  },
  {
    home: 'Botafogo',
    away: 'Corinthians',
    homeScore: 0,
    awayScore: 0,
    date: '2025-03-08',
    time: '21:00',
    venue: 'Nilton Santos',
    round: 6,
    status: 'SCHED',
  },
  {
    home: 'Fortaleza',
    away: 'Vasco',
    homeScore: 0,
    awayScore: 0,
    date: '2025-03-09',
    time: '16:00',
    venue: 'Castelão',
    round: 6,
    status: 'SCHED',
  },
  {
    home: 'Grêmio',
    away: 'Cruzeiro',
    homeScore: 0,
    awayScore: 0,
    date: '2025-03-09',
    time: '18:30',
    venue: 'Arena do Grêmio',
    round: 6,
    status: 'SCHED',
  },
  {
    home: 'Atlético-MG',
    away: 'Santos',
    homeScore: 0,
    awayScore: 0,
    date: '2025-03-09',
    time: '18:30',
    venue: 'Arena MRV',
    round: 6,
    status: 'SCHED',
  },
  {
    home: 'Sport',
    away: 'Bahia',
    homeScore: 0,
    awayScore: 0,
    date: '2025-03-09',
    time: '20:00',
    venue: 'Ilha do Retiro',
    round: 6,
    status: 'SCHED',
  },
  {
    home: 'Bragantino',
    away: 'Coritiba',
    homeScore: 0,
    awayScore: 0,
    date: '2025-03-09',
    time: '20:00',
    venue: 'Nabi Abi Chedid',
    round: 6,
    status: 'SCHED',
  },
  {
    home: 'Remo',
    away: 'Vitória',
    homeScore: 0,
    awayScore: 0,
    date: '2025-03-09',
    time: '20:00',
    venue: 'Mangueirão',
    round: 6,
    status: 'SCHED',
  },
  {
    home: 'Mirassol',
    away: 'Athletico-PR',
    homeScore: 0,
    awayScore: 0,
    date: '2025-03-09',
    time: '20:00',
    venue: 'Est. Campos Maia',
    round: 6,
    status: 'SCHED',
  },
];

// --- Jogo destaque (Hero) ---

export const JOGO_DESTAQUE = PROXIMOS_JOGOS_RODADA_6[0]; // Flamengo x Palmeiras
